services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sensor_metrics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sensor_metrics"]
      interval: 2s
      timeout: 2s
      retries: 15
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sensor_metrics
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Initializing database...' &&
        python scripts/init_database.py &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    restart: unless-stopped

volumes:
  postgres_data: